### ISSUE TITLE
Calculate digest of received request body

### ISSUE THREAD

**Issue by eadmundo** [autotelic/fastify-hmac#10]
At the moment when we construct the signature for verification in the default `constructSignatureString` method, we simply take the `Digest` header from the request and use the value directly. We should in fact be calculating our own digest from the request body - either to use in constructing the signature to verify, or to compare directly to the received `Digest` value

**Comment by eadmundo** [comment]
@jkirkpatrick24 from your reading of the spec, should we be comparing our calculated digest against the value received, or using it to construct the signature?

**Comment by jkirkpatrick24** [comment]
I think you're right, we need to calculate the digest from the request body, rather than trusting the `Digest` header.
