### ISSUE TITLE
Refactor ConstructSignatureString into separate methods

### ISSUE THREAD

**Issue by jeff-sexton** [autotelic/fastify-hmac#22]
The top-level method `constructSignatureString` is comprised of two functions: `calculateSignature` and `getMessage`. `calculateSignature` is simply called with the input from other methods or options and all of these parameters are part of the plugin options object with the exception of `getMessage`.

For the Shopify example, `constructSignatureString` is overridden with `constructShopifySignature` but the `calculateSignature`function remains essentially unchanged. It is the `getMessage` function that is different for the Shopify implementation.

Should we pull the `getMessage` function out into a separate top-level method that is called by `constructSignatureString` from the options object? 

`getMessage` could be renamed along the lines of `getSignatureInput` for clarity. 

The Shopify example functions and fastify server would also need to be refactored to match this pattern.

**Comment by jkirkpatrick24** [comment]
Similar to #24, I think we want to avoid overloading the options object if possible. Maybe we can expose some utils functions that other developers can use, but I don't know if its worth adding additional methods to our options.
