### ISSUE TITLE
Refactor parseSignatureHeader and include in plugin Options object

### ISSUE THREAD

**Issue by jeff-sexton** [autotelic/fastify-hmac#24]
Needs discussion:

The `parseSignatureHeader` function is currently used in three top-level default methods as a helper. Should this be refactored into a `parseSignature` method in the top-level options object?

**Comment by jkirkpatrick24** [comment]
Yeah that could be one way to do it. I don't really know what the main benefit would be though. We never would call it for under the hood for someone (like we do with the other defaults), unless the user were to override our default and no other default methods that use it under the hood. It may be a useful refactor if we thinks its worth it but I also think we should be wary of adding too much to the options object. We don't want it to become overloaded.
